framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async

            # Route your messages to the transports
            'App\Message\*': sync
            # Added here and should be set to async in future
            'App\Message\SendMessage': sync


# 2x: Since zenstruck/messenger-test 1.8.0: Not supporting DelayStamp is deprecated, support will be removed in 2.0.
# 2x in MessageControllerTest::testThatItSendsAMessage from Controller
# I found that support of delly stamp should be explicitly declared to avoid this warning
# even if it is not used.
when@test:
    framework:
        messenger:
            transports:
                async: test://?support_delay_stamp=true
                sync: test://?support_delay_stamp=true
